label hospitalGo:
    $ftecounter = 5
    blank "TODO: Spicy scene from the past here."
    scene blank
    bi "..."
    bi "As I slowly gained consciousness, I resisted opening my eyes."
    bi "Was I a child with no sense of object permanence?"
    bi "Maybe if I don't open my eyes this game won't continue?"
    bi "No, that's not it..."
    bi "I felt more like a student during finals week."
    bi "Exhausted from the first few, knowing I still had more to go."
    bi "Knowing hat the light at the end of the tunnel was very far away."
    bi "Wanting to cling to the relief of my bed, a temporary escape."
    bi "Except instead of finals, I had to solve the murders of people I was..."
    bi "Well, in some cases friends, others acquaintances."
    bi "Regardless, you never really know what death is like until you experience it in person."
    bi "I'm no different than anyone else growing up in the modern age of media and the internet."
    bi "I haven't seen the darkest of what's out there, but I've seen pictures of dead bodies."
    bi "Not willingly always, but I've seen them."
    bi "Didn't faze me one bit."
    bi "But in person? When it's someone you know?"
    bi "The smell, the way it looks like they're sleeping but they're not"
    bi "Feeling like you haven't seen them in a while and then the gut punch of remembering why."
    bi "I don't know how doctors, police, and morticians cope."
    bi "It's something I hope I never get used to."
    bi "..."
    ses "Mrowww!"
    bi "An angry hiss."
    bi "Right, I'm an unwilling cat owner now."
    bi "I found the energy to open my eyes."
    scene bg hospital cell with dissolve
    show sesame with dissolve
    ses "Mew!"
    b "Hey Sesame... sorry, I'm a bit tired."
    ses "Hssss!"
    bi "If I had to guess, he was pointing to the doors of the cell."
    bi "...A cell?"
    bi "Are we in a prison?"
    bi "There's doors on both sides, I don't think a prison would be like that."
    b "You want me to get us out of here?"
    ses "Hsss!"
    bi "Does he... understand the fact that Catherine's dead?"
    bi "Maybe he thinks I catnapped him?"
    bi "Whatever, that's not important right now."
    bi "I approached one door and tried opening it."
    bi "...it's locked."
    bi "Am I stuck in here? Did I wake up before I was supposed to?"
    bi "...Wait, if that's the case, maybe I can find out who the Game Master is!"
    bi "Maybe I can escape!"
    bi "Those thoughts quickly faded when I tried the second door."
    blank "Click."
    b "C'mon Sesame, let's go."
    ses "..."
    b "..."
    bi "Sesame wasn't moving."
    b "Lazy cat, Catherine probably carries you everywhere."
    b "Fine, I'll carry you around just for now. But don't get used to it."
    bi "I gently picked him up, scared he might scratch me."
    bi "He was gentler now though. Maybe hearing Catherine's name made him think we were going to her."
    bi "Eventually I'll have to get him used to me being his owner but..."
    bi "...until this game's over, there's far more important things to worry about."
    scene black with dissolve
    scene bg hospital hall with dissolve
    bi "It opened into a hallway."
    bi "There were three other cells in this hallway."
    bi "As I walked past them towards the sound of voices, I noticed they were empty."
    bi "Was I the last one to leave a cell?"
    scene black with dissolve
    scene bg hospital cafeteria with dissolve
    bi "The hallway opened up into what looked like a middle school cafeteria."
    bi "There, I saw everyone else gathered."
    show jenny happy with dissolve
    j "Morning Bert! Morning Sesame!"
    b "Good... morning? Do we know what time it is?"
    j "Nope! But you look like you just woke up from a long nap!"
    b "Uh... where are we?"
    j "Read the sign on the wall dummy!"
    bi "She pointed to where a few of the others were congegrating around a large sign."
    bi "They seemed to be discussing it. I walked over and joined the others around it."
    hide jenny with dissolve
    show lauren ind with dissolve
    l "Oh, hey Bert. How's Sesame treating you."
    b "I... think he thinks I stole him."
    l "I mean, you kind of did in a certain sense."
    l "Anyway, we were just discussing the rules, you should read them and get up to speed."
    b "Are... are we not going to discuss everything that just happened?"
    b "Catherine and Stella's... passing."
    bi "I said the last word quietly since Froggy was nearby."
    b "All the new info we learned?"
    l "Oh, we discussed that sleepyhead."
    l "If you woke up earlier you could've joined us."
    l "But the more pressing thing right now is where we are."
    bi "I turned from the group and looked at the sign."
    hide lauren with dissolve
    blank "Rules of the Mental Hospital"
    bi "...mental hospital?"
    bi "I guess... in a demented sense, a mental hospital is like a prison."
    blank "1. Every day, two guards will be appointed."
    blank "You will know you are a guard if you wake up and the door to the guard's side of this floor is open."
    blank "Otherwise, the door to the patients' side will be open."
    blank "2. After the first day, you may not be in your cell except at night."
    blank "An intercom will announce when night begins."
    blank "It will also announce when there are 30, 5, and 1 minute of night left if someone has failed to leave."
    blank "You will be killed if you fail to exit your cell on time."
    blank "You may still roam freely in areas besides your cell that you have access to at night."
    blank "However, if night ends and your feet are in the guard area while designated as a patient or vice-versa..."
    blank "...you will be killed."
    blank "3. Guards are responsible for feeding the patients during the day."
    blank "They may do this however they please, using the kitchen connected to this cafeteria."
    blank "4. No one is permitted to enter the cell of another individual, even at night."
    blank "If you enter another individual's cell, you will be killed."
    bi "..."
    bi "As if this game wasn't hard enough as is."
    bi "Is the Game Master upset we had a party? Wants to keep us in check?"
    bi "Lauren called out to me from the group she was talking to."
    show lauren ind with dissolve
    l "Finished reading?"
    b "Yeah. It's a lot to process."
    l "Thoughts?"
    bi "I moved to join in on the conversation."
    show sid ind:
        xcenter .25
    show drac ind:
        xcenter .75
    with dissolve
    b "Well, one line sticks out to me."
    b "The fact that the guards are in charge of feeding people."
    b "What if they just don't feed us. Do we starve to death?"
    b "Also, it seems like a guard would never be able to commit murder."
    b "You could only get in touch with the other guard, and if you murdered them..."
    b "Well, we'd all vote for you in a heartbeat since you're the only one who could reach them."
    d "The fact that guards feed us could be the intended mechanism for guards to kill patients."
    l "Why do you say that?"
    d "Think about it."
    d "It will be hard for patients to murder each other, given this seems to be the only common area we have."
    d "That, and we can't enter each other's cells."
    d "A patient murdering another patient would likely have to do it in front of others..."
    d "So despite Bert's argument, it will likely no easier to commit murder as a patient."
    d "But Bert is right that it is unlikely a guard will try to kill another guard."
    d "So the guards need to somehow be able to kill patients."
    d "They could poison someone's food, or starve someone to death..."
    i "Wait, I don't think starvation would be a good murder method."
    i "Unless someone gets to be the guard multiple days in a row, we could last one day without food."
    i "It sucks but... I've done it before."
    d "Fair. I'm just postulating. We should check our food carefully and such."
    bi "If the mansion is any evidence, I don't think people will stay on guard just because Dracula said to..."
    b "Dracula mentioned this is the only common area for patients. Have you all checked that?"
    l "Yeah, there's a bathroom in here but besides that..."
    l "The only rooms we can access right now are this room, the hallways, and our cells."
    l "It sounds like we won't be able to access the guards' area until tomorrow."
    i "Speaking of one day without food..."
    l "Yeah, don't think we're eating tonight."
    l "Hopefully the announcement for night is soon."
    i "Sleep for dinner..."
    ses "Mew?"
    bi "Oh, right, I have to feed Sesame too..."
    bi "I hope he doesn't hiss at me through the night because he's hungry..."
    b "So um... now that we've discussed the sign can someone catch me up on what you discussed without me?"
    d "If I must..."
    l "I can do it if you don't want to."
    d "Fine with me. I wished to check on Sam anyway."
    hide drac with dissolve
    i "I think I'll go too..."
    hide sid with dissolve
    b "Check on Sam?"
    l "Oh, I guess you and Sam haven't talked yet..."
    l "Take a look."
    bi "I looked over and saw Jenny, Sam, Shahar, and Freddy talking."
    bi "Well, Jenny and Freddy were doing all the talking."
    bi "Shahar was lost in thought."
    bi "...huh? Since when was Shahar the type to get lost in thought?"
    bi "Maybe Stella's death hit him harder than we expected."
    bi "And Sam was... sulking, it seemed."
    l "Sam's overwhelmed with guilt."
    l "I guess attempting to murder someone will do that to you."
    l "You should talk to Sam when you can. I think we really need to get Sam to open up if we can."
    l "As annoying as hearing Sam talk usually is... it's helpful in its own way."
    b "You really think so?"
    l "Yeah. Even if we don't always agree, having persistent people is probably the only way we get out of here."
    bi "I guess there are only eight of us left..."
    bi "Everyone is an even more valuable member of this \"team\" at this point."
    bi "Well, except the Game Master..."
    b "Hey um... why is Jenny taking care of Freddy right now?"
    l "Oh, uh..."
    l "Okay, when Dan and Kaiser died I think the reality of the game hadn't really settled in for me."
    l "I barely talked to them, they both had kind of abrasive personalities."
    l "It was easy to process their deaths by telling myself nothing of value was lost."
    l "And even with Stella's dead, I could tell that lie to myself."
    l "She was nice sometimes, but she was still abrasive, albeit in a different way."
    l "But Catherine..."
    l "I liked her. Or at least, the version of her we knew."
    l "And it made me realize... I could be the next to go."
    l "And if that happens, Freddy needs someone else to rely on."
    l "So I'm trying to trust others to take care of him more than I have."
    b "Makes sense... and Jenny is I guess the next best person to take care of him."
    l "Maybe. But what if she goes too?"
    l "What if it's just Shahar, Sam, and Dracula taking care of Freddy?"
    l "Would any of them even give him the time of day?"
    l "Shahar's too aloof, Sam's not even talking at this point."
    l "Dracula... might suspect Freddy of being the Game Master if he makes it that far."
    b "..."
    b "Lauren, I'm going to live as long as I can in this game."
    b "And I'll make sure that Freddy lives with me too."
    l "That's nice Bert, but how can you possible guarantee that?"
    b "I... I..."
    b "I guess I can't..."
    l "Exactly."
    bi "..."
    bi "Damn. I'd never felt so useless in this game."
    bi "It's easy to feel useful while solving murder mysteries but..."
    bi "Solving them doesn't change the fact that we're dying one by one."
    bi "It just slows down the deaths for a while..."
    bi "Nothing I can do can stop one more person from dying while we're here."
    l "Anyway, we should discuss what we learned from Catherine, like I promised."
    b "...right, yeah."
    l "So Bert, have you ever met Mr. Sydell?"
    b "No, I don't think I heard of him until we were in the mansion."
    l "Yeah, figured as much."
    l "It seems like the only people who knew him, or at least are admitting to it are..."
    l "Well, Stella, Sam, and Catherine."
    l "Shahar told us what Stella said to you while drinking at the mansion."
    l "About how her company had some lawsuit with him."
    l "So both Catherine and Stella damaged him in some way."
    l "If just Catherine knew him, it wouldn't mean a lot."
    l "It would be about as useful as knowing Kaiser robbed that train."
    l "A fact that seems totally irrelevant to where we are now."
    l "But Stella being an enemy of Mr. Sydell, but not being chosen to murder him..."
    b "You think maybe Mr. Sydell organized this game? To get revenge on all of us?"
    l "Well, Dracula had this theory."
    l "I don't know if I fully agree. After all, Sam just sold drugs to him."
    l "Is that something he would want revenge for?"
    l "I'm not a junkie, but my understanding is he'd feel like Sam was doing him a favor, no?"
    b "Hard to say without knowing more about their relationship."
    l "Yeah, well, Sam's not really talking enough for us to find out."
    b "Another thing... if Mr. Sydell is the Game Master... why isn't he here?"
    b "We were promised the Game Master was one of us."
    l "Dunno. Maybe that was a lie?"
    b "If it's a lie, doesn't that mean we can't win this game?"
    l "Maybe. It wouldn't be surprising to me if that were the case."
    l "This game isn't exactly fair even if the Game Master is here..."
    b "...do we just keep trying then?"
    b "What's the point if there's no Game Master to let us end the game?"
    l "Hey, maybe the whole Sydell theory is wrong."
    l "And not like we have anything better to do."
    b "No, don't worry, I'm not giving up just..."
    b "Seems kind of useless to consider that possibility, I guess."
    l "Maybe. It's just a possibility."
    l "Anyway, I sure as hell am not planning to murder anyone here, so it doesn't really help me."
    l "But if you're planning to murder someone, I guess that's the lead we have."
    l "Oh, we're also pretty sure there's gonna be another location-based advantage."
    l "Keep that in mind, when we get to explore the guard's side we might have a guess for what it is."
    l "If we can figure it out it might make solving the mystery easier for all of us."
    bi "She says \"all of us,\" but it's really been me doing most of the solving..."
    b "Sounds like a plan. Anything else I should know?"
    l "Not really, that's most of the \"strategy\" stuff we discussed a group."
    l "There's a lot of emotions running around about Stella and Catherine but..."
    l "Well, I don't want to speak on behalf of anyone emotionally."
    l "Shahar and Sam seem to be the most affected, if you're looking to play shrink to kill some time."
    b "I... wouldn't know what to say to either."
    l "That's fine, I'm not telling you that you have to. Just something to consider."
    b "Thanks Lauren, for catching me up."
    l "No problem. I'm gonna go join the others, ciao."
    hide lauren with dissolve
