label hospitalGo:
    $ftecounter = 5
    blank "TODO: Spicy scene from the past here."
    scene black
    bi "..."
    bi "As I slowly gained consciousness, I resisted opening my eyes."
    bi "Was I a child with no sense of object permanence?"
    bi "Maybe if I don't open my eyes this game won't continue?"
    bi "No, that's not it..."
    bi "I felt more like a student during finals week."
    bi "Exhausted from the first few, knowing I still had more to go."
    bi "Knowing hat the light at the end of the tunnel was very far away."
    bi "Wanting to cling to the relief of my bed, a temporary escape."
    bi "Except instead of finals, I had to solve the murders of people I was..."
    bi "Well, in some cases friends, others acquaintances."
    bi "Regardless, you never really know what death is like until you experience it in person."
    bi "I'm no different than anyone else growing up in the modern age of media and the internet."
    bi "I haven't seen the darkest of what's out there, but I've seen pictures of dead bodies."
    bi "Not willingly always, but I've seen them."
    bi "Didn't faze me one bit."
    bi "But in person? When it's someone you know?"
    bi "The smell, the way it looks like they're sleeping but they're not"
    bi "Feeling like you haven't seen them in a while and then the gut punch of remembering why."
    bi "I don't know how doctors, police, and morticians cope."
    bi "It's something I hope I never get used to."
    bi "..."
    ses "Mrowww!"
    bi "An angry hiss."
    bi "Right, I'm an unwilling cat owner now."
    bi "I found the energy to open my eyes."
    scene bg hosproom1 with dissolve
    show sesame with dissolve
    ses "Mew!"
    b "Hey Sesame... sorry, I'm a bit tired."
    ses "Hssss!"
    bi "If I had to guess, he was pointing to the doors of the cell."
    bi "...A cell?"
    bi "Are we in a prison?"
    bi "There's doors on both sides, I don't think a prison would be like that."
    b "You want me to get us out of here?"
    ses "Hsss!"
    bi "Does he... understand the fact that Catherine's dead?"
    bi "Maybe he thinks I catnapped him?"
    bi "Whatever, that's not important right now."
    bi "I approached one door and tried opening it."
    bi "...it's locked."
    bi "Am I stuck in here? Did I wake up before I was supposed to?"
    bi "...Wait, if that's the case, maybe I can find out who the Game Master is!"
    bi "Maybe I can escape!"
    bi "Those thoughts quickly faded when I tried the second door."
    blank "Click."
    b "C'mon Sesame, let's go."
    ses "..."
    b "..."
    bi "Sesame wasn't moving."
    b "Lazy cat, Catherine probably carries you everywhere."
    b "Fine, I'll carry you around just for now. But don't get used to it."
    bi "I gently picked him up, scared he might scratch me."
    bi "He was gentler now though. Maybe hearing Catherine's name made him think we were going to her."
    bi "Eventually I'll have to get him used to me being his owner but..."
    bi "...until this game's over, there's far more important things to worry about."
    scene black with dissolve
    scene bg hosphall1 with dissolve
    bi "It opened into a hallway."
    bi "There were three other cells in this hallway."
    bi "As I walked past them towards the sound of voices, I noticed they were empty."
    bi "Was I the last one to leave a cell?"
    scene black with dissolve
    scene bg hospcommons with dissolve
    bi "The hallway opened up into what looked like a middle school cafeteria."
    bi "There, I saw everyone else gathered."
    show jenny happy with dissolve
    j "Morning Bert! Morning Sesame!"
    b "Good... morning? Do we know what time it is?"
    j "Nope! But you look like you just woke up from a long nap!"
    b "Uh... where are we?"
    j "Read the sign on the wall dummy!"
    bi "She pointed to where a few of the others were congegrating around a large sign."
    bi "They seemed to be discussing it. I walked over and joined the others around it."
    hide jenny with dissolve
    show lauren ind with dissolve
    l "Oh, hey Bert. How's Sesame treating you."
    b "I... think he thinks I stole him."
    l "I mean, you kind of did in a certain sense."
    l "Anyway, we were just discussing the rules, you should read them and get up to speed."
    b "Are... are we not going to discuss everything that just happened?"
    b "Catherine and Stella's... passing."
    bi "I said the last word quietly since Froggy was nearby."
    b "All the new info we learned?"
    l "Oh, we discussed that sleepyhead."
    l "If you woke up earlier you could've joined us."
    l "But the more pressing thing right now is where we are."
    bi "I turned from the group and looked at the sign."
    hide lauren with dissolve
    blank "Rules of the Mental Hospital"
    bi "...mental hospital?"
    bi "I guess... in a demented sense, a mental hospital is like a prison."
    blank "1. Every day, two guards will be appointed."
    blank "You will know you are a guard if you wake up and the door to the guard's side of this floor is open."
    blank "Otherwise, the door to the patients' side will be open."
    blank "2. After the first day, you may not be in your cell except at night."
    blank "An intercom will announce when night begins."
    blank "It will also announce when there are 30 minutes left."
    blank "There will be two more announcements when there are 5 and 2 minutes of night left if someone has failed to leave."
    blank "You will be killed if you fail to exit your cell on time."
    blank "You may still roam freely in areas besides your cell that you have access to at night."
    blank "However, if night ends and your feet are in the guard area while designated as a patient or vice-versa..."
    blank "...you will be killed."
    blank "3. Guards are responsible for feeding the patients during the day."
    blank "They may do this however they please, using the kitchen connected to this cafeteria."
    blank "4. No one is permitted to enter the cell of another individual, even at night."
    blank "If you enter another individual's cell, you will be killed."
    bi "..."
    bi "As if this game wasn't hard enough as is."
    bi "Is the Game Master upset we had a party? Wants to keep us in check?"
    bi "Lauren called out to me from the group she was talking to."
    show lauren ind with dissolve
    l "Finished reading?"
    b "Yeah. It's a lot to process."
    l "Thoughts?"
    bi "I moved to join in on the conversation."
    show sid ind:
        xcenter .25
    show drac ind:
        xcenter .75
    with dissolve
    b "Well, one line sticks out to me."
    b "The fact that the guards are in charge of feeding people."
    b "What if they just don't feed us. Do we starve to death?"
    b "Also, it seems like a guard would never be able to commit murder."
    b "You could only get in touch with the other guard, and if you murdered them..."
    b "Well, we'd all vote for you in a heartbeat since you're the only one who could reach them."
    d "The fact that guards feed us could be the intended mechanism for guards to kill patients."
    l "Why do you say that?"
    d "Think about it."
    d "It will be hard for patients to murder each other, given this seems to be the only common area we have."
    d "That, and we can't enter each other's cells."
    d "A patient murdering another patient would likely have to do it in front of others..."
    d "So despite Bert's argument, it will likely no easier to commit murder as a patient."
    d "But Bert is right that it is unlikely a guard will try to kill another guard."
    d "So the guards need to somehow be able to kill patients."
    d "They could poison someone's food, or starve someone to death..."
    i "Wait, I don't think starvation would be a good murder method."
    i "Unless someone gets to be the guard multiple days in a row, we could last one day without food."
    i "It sucks but... I've done it before."
    d "Fair. I'm just postulating. We should check our food carefully and such."
    bi "If the mansion is any evidence, I don't think people will stay on guard just because Dracula said to..."
    b "Dracula mentioned this is the only common area for patients. Have you all checked that?"
    l "Yeah, there's a bathroom in here but besides that..."
    l "The only rooms we can access right now are this room, the hallways, and our cells."
    l "It sounds like we won't be able to access the guards' area until tomorrow."
    i "Speaking of one day without food..."
    l "Yeah, don't think we're eating tonight."
    l "Hopefully the announcement for night is soon."
    i "Sleep for dinner..."
    ses "Mew?"
    bi "Oh, right, I have to feed Sesame too..."
    bi "I hope he doesn't hiss at me through the night because he's hungry..."
    b "So um... now that we've discussed the sign can someone catch me up on what you discussed without me?"
    d "If I must..."
    l "I can do it if you don't want to."
    d "Fine with me. I wished to check on Sam anyway."
    hide drac with dissolve
    i "I think I'll go too..."
    hide sid with dissolve
    b "Check on Sam?"
    l "Oh, I guess you and Sam haven't talked yet..."
    l "Take a look."
    bi "I looked over and saw Jenny, Sam, Shahar, and Freddy talking."
    bi "Well, Jenny and Freddy were doing all the talking."
    bi "Shahar was lost in thought."
    bi "...huh? Since when was Shahar the type to get lost in thought?"
    bi "Maybe Stella's death hit him harder than we expected."
    bi "And Sam was... sulking, it seemed."
    l "Sam's overwhelmed with guilt."
    l "I guess attempting to murder someone will do that to you."
    l "You should talk to Sam when you can. I think we really need to get Sam to open up if we can."
    l "As annoying as hearing Sam talk usually is... it's helpful in its own way."
    b "You really think so?"
    l "Yeah. Even if we don't always agree, having persistent people is probably the only way we get out of here."
    bi "I guess there are only eight of us left..."
    bi "Everyone is an even more valuable member of this \"team\" at this point."
    bi "Well, except the Game Master..."
    b "Hey um... why is Jenny taking care of Freddy right now?"
    l "Oh, uh..."
    l "Okay, when Dan and Kaiser died I think the reality of the game hadn't really settled in for me."
    l "I barely talked to them, they both had kind of abrasive personalities."
    l "It was easy to process their deaths by telling myself nothing of value was lost."
    l "And even with Stella's dead, I could tell that lie to myself."
    l "She was nice sometimes, but she was still abrasive, albeit in a different way."
    l "But Catherine..."
    l "I liked her. Or at least, the version of her we knew."
    l "And it made me realize... I could be the next to go."
    l "And if that happens, Freddy needs someone else to rely on."
    l "So I'm trying to trust others to take care of him more than I have."
    b "Makes sense... and Jenny is I guess the next best person to take care of him."
    l "Maybe. But what if she goes too?"
    l "What if it's just Shahar, Sam, and Dracula taking care of Freddy?"
    l "Would any of them even give him the time of day?"
    l "Shahar's too aloof, Sam's not even talking at this point."
    l "Dracula... might suspect Freddy of being the Game Master if he makes it that far."
    b "..."
    b "Lauren, I'm going to live as long as I can in this game."
    b "And I'll make sure that Freddy lives with me too."
    l "That's nice Bert, but how can you possible guarantee that?"
    b "I... I..."
    b "I guess I can't..."
    l "Exactly."
    bi "..."
    bi "Damn. I'd never felt so useless in this game."
    bi "It's easy to feel useful while solving murder mysteries but..."
    bi "Solving them doesn't change the fact that we're dying one by one."
    bi "It just slows down the deaths for a while..."
    bi "Nothing I can do can stop one more person from dying while we're here."
    l "Anyway, we should discuss what we learned from Catherine, like I promised."
    b "...right, yeah."
    l "So Bert, have you ever met Mr. Sydell?"
    b "No, I don't think I heard of him until we were in the mansion."
    l "Yeah, figured as much."
    l "It seems like the only people who knew him, or at least are admitting to it are..."
    l "Well, Stella, Sam, and Catherine."
    l "Shahar told us what Stella said to you while drinking at the mansion."
    l "About how her company had some lawsuit with him."
    l "So both Catherine and Stella damaged him in some way."
    l "If just Catherine knew him, it wouldn't mean a lot."
    l "It would be about as useful as knowing Kaiser robbed that train."
    l "A fact that seems totally irrelevant to where we are now."
    l "But Stella being an enemy of Mr. Sydell, but not being chosen to murder him..."
    b "You think maybe Mr. Sydell organized this game? To get revenge on all of us?"
    l "Well, Dracula had this theory."
    l "I don't know if I fully agree. After all, Sam just sold drugs to him."
    l "Is that something he would want revenge for?"
    l "I'm not a junkie, but my understanding is he'd feel like Sam was doing him a favor, no?"
    b "Hard to say without knowing more about their relationship."
    l "Yeah, well, Sam's not really talking enough for us to find out."
    b "Another thing... if Mr. Sydell is the Game Master... why isn't he here?"
    b "We were promised the Game Master was one of us."
    l "Dunno. Maybe that was a lie?"
    b "If it's a lie, doesn't that mean we can't win this game?"
    l "Maybe. It wouldn't be surprising to me if that were the case."
    l "This game isn't exactly fair even if the Game Master is here..."
    b "...do we just keep trying then?"
    b "What's the point if there's no Game Master to let us end the game?"
    l "Hey, maybe the whole Sydell theory is wrong."
    l "And not like we have anything better to do."
    b "No, don't worry, I'm not giving up just..."
    b "Seems kind of useless to consider that possibility, I guess."
    l "Maybe. It's just a possibility."
    l "Anyway, I sure as hell am not planning to murder anyone here, so it doesn't really help me."
    l "But if you're planning to murder someone, I guess that's the lead we have."
    l "Oh, we're also pretty sure there's gonna be another location-based advantage."
    l "Keep that in mind, when we get to explore the guard's side we might have a guess for what it is."
    l "If we can figure it out it might make solving the mystery easier for all of us."
    bi "She says \"all of us,\" but it's really been me doing most of the solving..."
    b "Sounds like a plan. Anything else I should know?"
    l "Not really, that's most of the \"strategy\" stuff we discussed a group."
    l "There's a lot of emotions running around about Stella and Catherine but..."
    l "Well, I don't want to speak on behalf of anyone emotionally."
    l "Shahar and Sam seem to be the most affected, if you're looking to play shrink to kill some time."
    b "I... wouldn't know what to say to either."
    l "That's fine, I'm not telling you that you have to. Just something to consider."
    bi "...Well, now I feel like she really wants me to."
    b "Thanks Lauren, for catching me up."
    l "No problem. I'm gonna go join the others, ciao."
    hide lauren with dissolve
    bi "I guess even if I can't help them feel better, I should know what's going on..."
    bi "If they're going to be liabilities... no, I shouldn't think like that."
    bi "Let's see, Shahar or Sam..."
    $menuset = set()
    menu samorshahar:
        set menuset
        "Who should I talk to?"

        "Talk to Sam."
            show sam with dissolve
            s "Oh... hey Bert."
            b "Hey Sam... how are you feeling?"
            s "I don't know, I just tried to kill someone because I thought I had to."
            s "But then I found out I didn't have to, I'm just an idiot."
            s "So now I'm someone who murdered without a good reason."
            s "So what do you think, that I'm feeling fine?"
            bi "Still sassy, even when feeling sad..."
            bi "But I guess it was a dumb question."
            b "Sam... you didn't kill Stella. Catherine did."
            s "I may as well have."
            s "Catherine got lucky that I pushed Stella into her trap."
            s "If Stella's standing one foot to the right when I stab her..."
            s "I'm the one who killed her, and Catherine has nothing to do with it."
            s "Murder isn't a card game Bert."
            s "You don't avoid murdering someone on a technicality."
            s "Even if I make it out of this hellhole, I'm a murderer for the rest of my life."
            s "My mother and father will celebrate holidays with a murderer."
            s "If I want to have kids, they'll be raised by a murderer."
            b "You didn't know."
            b "If you were the designated murderer and Stella was the mastermind, you'd have saved our lives."
            s "Bert, have you ever murdered someone?"
            b "I mean-"
            s "{i}Willingly{/i} murdered someone?"
            b "...No."
            s "Then don't try to act like anything will absolve me of being a murderer for the rest of my life."
            s "We're done talking."
            s "Just avoid me like everyone else has this whole time."
            s "I'm not worth trying to save."
            s "At best, I'm another warm body that the murderer can kill."
            b "..."
            b "Fine, I'll leave you alone."
            b "But all our lives are on the line here, not just yours."
            b "We're still relying on you to help us escape."
            b "If you're going to feel bad about Stella, don't let that happen to the rest of us."
            s "..."
            s "Whatever."
            hide sam with dissolve
            bi "Well, I guess that's that..."
            jump samorshahar

        "Talk to Shahar."
            show shahar mad with dissolve
            h "Aye lad."
            b "Hey Shahar. Lauren told me you weren't feeling great?"
            h "Aye. I feel like my head is made of the ocean mist."
            b "Wait..."
            b "Because Stella died?"
            h "Oh, that lassie?"
            h "I miss her, but I've lost many compatriots on the sea."
            h "I only knew 'er for nary a week, Bert, it's not like I lost me lover or me parent."
            h "But... I feel like I'm forgetting somethin', lad."
            h "Well, nay."
            h "It's more like... I can't remember somethin'."
            h "I feel like I don't know who I am, lad."
            b "Huh."
            b "You haven't felt this way until now"?
            bi "Because I knew I didn't know who you were the whole time..."
            h "Nay lad. Something about this place..."
            h "It feels like this is a room in a pirate ship I've wandered 'round."
            b "But... it's a hospital."
            h "Aye lad, you can see my confusion."
            h "Pirates don't need hospitals, a lil' scurvy hurt nary a man of the sea!"
            bi "Uh... I don't think that's true."
            bi "Also, this is a mental hospital. Scurvy doesn't get treated here..."
            h "Anyway lad, my head's been hurtin'."
            h "Not just because I can't 'member, lad."
            h "I got a headache like I drank a gallon o' bilge water."
            h "And I'm not much of a thinker so..."
            h "I ain't got any idea what to do."
            b "That's... frustrating. I don't know what to tell you."
            b "Tomorrow let's ask the guards to see if there's any pain relievers."
            h "See lad, that's the kind of thinkin' I need ye fer!"
            bi "Ah yes, the obscure idea of taking medicine to help with a headache."
            b "And maybe we can find out why you think you remember this place if we get out of here?"
            h "Aye lad, maybe. Guess I'll spend what little brain cells I have on that endeavor."
            bi "With that, I left him to think. Or not think, not sure which."
            hide shahar with dissolve
            jump samorshahar
    bi "Having talked to Sam and Shahar, I went to go join the others."
    bi "But a noise interrupted."
    play sfx "audio/ding.mp3"
    intercom "It is now nighttime. Please feel free to return to your rooms."
    intercom "You may still roam freely, but remember that you must leave your cell before night ends."
    show jenny ind:
        xcenter .25
    show frog ind:
        xcenter .75
    j "Well, guess we should all go sleep."
    f "But... I don't wanna. I wanna play!"
    j "C'mon Froggy, we only have a few hours where we're allowed to be in bed."
    j "If you don't sleep now, you'll be tired tomorrow."
    f "F-fine..."
    f "Can I at least sleep in Lauren's room?"
    j "No Freddy, we all have to sleep in our own rooms."
    f "B-but..."
    show frog sad:
        xcenter .75
    f "But I haven't played with her at all."
    f "And I'm scared someone will hurt me in my room."
    j "Don't worry Freddy, no one can go into your room."
    j "Your bed is in the same hall as Lauren's, remember?"
    j "She can pick you up in the morning and protect you."
    f "O...okay..."
    b "Oh, that reminds me."
    b "What's the room arrangement?"
    j "Oh yeah, I guess you were the last to arrive."
    show map3ui with dissolve:
        alpha 0.5
        xcenter .5
        ycenter .5
    j "So there's two hallways, one to the left of the room we're in if you're facing the kitchen."
    j "That one has Lauren, Sam, Dracula, and Froggy, going from furthest to closest to this room."
    j "The one on the right has me, you, Sid, and Shahar, going from closest to furthest."
    hide map3ui with dissolve
    show jenny happy:
        xcenter .25
    j "So you can be a gentleman and escort me to my room, Bert!"
    b "Very smooth. Sure, let's head that way."
    b "Good night Froggy. We'll see you very soon!"
    f "G-good night..."
    scene black with fade
    bi "We all made our way back to our rooms."
    bi "I had trouble sleeping."
    bi "Mostly because Sesame didn't like the cold floor and instead insisted on laying on me."
    bi "Turns out, she wasn't declawed."
    bi "Which is good, declawing cats is pretty inhumane."
    bi "But so is constantly poking me while I try to sleep."
    scene bg hosproom1 with dissolve
    bi "After what felt like not sleeping at all, I woke up."
    bi "Well, I was woken up."
    bi "By a sound I hoped I wouldn't get used to."
    play sfx "audio/ding.mp3"
    intercom "There are 30 minutes left in nighttime. You must leave your room before nighttime is over."
    bi "I knew if I stayed in bed, I might not make it out of the room in 30 minutes."
    bi "So I begrudgingly got up and tried opening the door."
    bi "..."
    bi "And, it wouldn't move."
    bi "Was I stuck? Am I getting indirectly murdered already?"
    ses "Mew!"
    show sesame with dissolve
    bi "Sesame was standing near the opposite door."
    bi "Right, I might be the guard today."
    b "Thanks Sesame."
    bi "I stepped outside into the hallway."
    bi "Guess it's time to explore."
    scene black with dissolve
    scene bg hosphall1 with dissolve
    show jenny happy with dissolve
    j "Oh, hey Bert! Hey Sesame!"
    j "Guess we're on guard duty today!"
    b "Oh, nice. I was kind of afraid I'd be paired with someone like Dracula..."
    j "Ha! Nope, just little old me."
    j "Don't get on my bad side though, or I'll have to make up stories about being a vampire to scare you away!"
    b "Please don't."
    j "Don't worry, I wouldn't even know how."
    j "So, whaddya wanna do first?"
    b "I think we have to make food for the others, but nighttime isn't even over yet."
    b "So I was thinking we should explore and tell the others what we find."
    j "Sounds like a plan!"
    b "Okay, let's see what's at the end of this hallway..."
    scene black with dissolve
    scene bg hospfancy with dissolve
    show jenny ind with dissolve
    j "Huh, what's this?"
    b "It looks like it's a common area for the guards."
    j "It's... so much nicer than the common area for the patients."
    j "A nice lighting fixture, a vending machine, some couches..."
    j "What looks like a window, except it's been boarded up..."
    b "I guess we can relax here after we've fed everyone if we want to."
    b "This kind of reminds me of that study on prisoners and guards though."
    b "Is the Game Master trying to get us to feel like we're better than them?"
    j "Oh that? I'm pretty sure the study was just egged on by the professor in charge."
    j "Crazy guy who more concerned with producing some publishable results than with being humane."
    j "Besides, we'll only be on this side for one day."
    j "Now c'mon, let's look around the room."
    j "We should probably start with these rules..."
    b "Oh god, is there stuff that can get us killed on this side too?"
    j "..."
    j "Hm, no, it's just a repeat of the rules on the other side."
    j "I guess we can't go into the common space for patients."
    j "So it makes sense to give us a copy to read in here."
    b "Psh, reading's boring, I'm tryna check out this vending machine."
    b "Maybe there's some cola in there..."
    b "I like a good classic cola, nothing beats that."
    b "Huh, this vending machine's very... old-timey."
    j "What makes you say that?"
    b "All the bottles are glass. It reminds me of how they package soda in foreign countries."
    b "But I don't think I've seen a vending machine with glass bottles where I'm from."
    j "Hm... I wonder how long ago this building was in use."
    j "Or maybe they just didn't have money to upgrade it?"
    j "Ooh, maybe the Game Master bought this place because they went bankrupt!"
    b "That's... a theory, not sure if we can infer from that, though."
    b "Besides \"The Game Master has money or influence.\""
    show jenny happy
    j "Hey, that's something!"
    bi "I... could've guessed that without seeing this vending machine."
    b "Well, there is cola in here, I'm gonna grab some!"
    play sfx "audio/beep.mp3"
    b "Huh? It's not vending..."
    show jenny ind
    j "Did you pay for the drink?"
    b "Pay? With what? Not like we have money here..."
    j "You could break the vending machine open if you really want to."
    b "That sounds dangerous..."
    b "Don't people die getting crushed by vending machines?"
    j "That's just a risk you'll have to take."
    b "..."
    b "Anyway, doesn't seem like there's much else in here?"
    b "Just some couches we could maybe take a nap on..."
    j "What, did you want to play video games or something in here?"
    b "I mean... I wouldn't say no..."
    show jenny happy
    j "You're so silly."
    play sfx "audio/ding.mp3"
    intercom "There are 5 minutes left in nighttime. You must leave your room before nighttime is over."
    show jenny ind
    j "Hm, seems like someone hasn't left their room yet."
    b "How do you know that?"
    j "The rules said we'd only hear the 5 minute and 2 minute announcement if someone was still in their room."
    b "Oh, that's true."
    b "I wonder who it is..."
    j "Oh, that probably means we should get working on food."
    j "We didn't eat anything yesterday, people are probably starving."
    blank "Brooorgh."
    j "What was that?"
    b "That... might have been my stomach."
    j "Case in point. I'm going to go to the kitchen, you should feel free to keep exploring."
    j "That way we make the most use of our time."
    b "If you say so..."
    show jenny happy
    j "No worries Bert, I cooked for us once, I don't mind doing it again."
    j "I think this door is to the kitchen, you should get out the other two doors in here."
    b "Sounds good. Thanks Jenny, I'll let you know what I find."
    hide jenny with dissolve
    bi "Alright, let's see what's behind door number one..."
    scene black with dissolve
    scene bg hospsecurity with dissolve
    b "..."
    b "What is this?"
    b "A computer system? This gives me bad flashbacks to the train..."
    bi "I don't know why I talked out loud when it was just me and Sesame."
    bi "Not like he could understand..."
    b "Let's try turning it on..."
    b "Hm, there isn't a login screen like on the train."
    b "Let's see, what's interesting..."
    b "Seems like there's a program they use to store patient information."
    b "Kind of like that program dentists use that stores your history, but it's... well, for a mental hospital."
    b "Then there's a security camera system."
    b "..."
    b "Yup, I can see the cafeteria from here."
    b "Everyone had gathered, Jenny was talking to Sid through the kitchen window."
    b "Hmm, it has an option to look at other rooms, but the button's not working."
    b "It'd be impossible to commit a murder if a guard was just looping through the cameras."
    b "The cafeteria is a hard place to pull off a murder, so it's not really too useful to have a camera there."
    b "The Game Master keeping things fair, I guess..."
    b "There's also a program that controls the utilities in the building."
    b "You can turn off the lights, there's something about cycling hot water through the plumbing system..."
    b "Change the temperature throughout the building..."
    b "Doesn't seem like there's any way to control the cell doors, the nighttime announcement, or anything useful though."
    b "It would be nice if we could roam freely..."
    b "Right now it's just me and Jenny..."
    b "..."
    b "She wouldn't kill me now, right?"
    b "Should I look out for her?"
    b "Anyone could be the murderer, including her..."
    b "No, I need to stop freaking out."
    b "If she killed me here it would be way too obvious."
    b "Plus, it's not like I can do anything about it, I'm stuck on this side with her."
    b "I should focus on being as useful as possible while I'm able to explore this side..."
    b "Speaking of which, time to move on."
    ses "Mew!"
    show sesame with moveinbottom
    hide sesame with moveoutbottom
    bi "Sesame jumped on the controls and then jumped off..."
    b "Huh? This is the program storing patient information."
    b "I guess I should take a look, maybe there's something useful here?"
    b "Maybe I should look for the name Sydell, see if he has a connection to this place too."
    b "..."
    b "No, it's just a bunch of names I don't recognize."
    b "This feels invasive... it's a lot of personal information about people I don't know."
    b "It'd be like looking at strangers' search histories, except it's their mental illnesses."
    b "..."
    b "Huh?"
    b "Why is Shahar's name in the patient records?"
    b "I had to scroll a few hundred lines to find his name. I almost missed it."
    b "Let me check the record..."
    b "..."
    b "His record is almost completely blank."
    b "All it says is \"Patient thinks he is a pirate.\""
    b "Nothing about who Shahar actually is, any contact information..."
    b "Is that the case for the other records?"
    b "Let me check one."
    b "Whoever Howard Eastnuts is, I'm sorry for looking..."
    b "..."
    b "This person has family contact information, a detailed medical history..."
    b "Date of admission, date of discharge, insurance information, prescriptions."
    b "And a bunch more details Shahar's profile here lacks."
    b "Was Shahar's profile inserted to freak me out? Was he actually a patient here?"
    b "Did someone wipe his information before we got here? Maybe the Game Master thought we'd learn too much?"
    b "Maybe Shahar is the Game Master and he's using this as a bluff?"
    b "I should check one more thing, just to be sure..."
    b "..."
    b "Nope, I've tried all of our names. Including Kaiser, Dan, Catherine, and Stella's."
    b "No one in this game except Shahar has a record here."
    b "I should talk to Shahar about this."
    b "This might have to do with his headache."
    b "Well, assuming he's not lying..."
    b "Should I tell the others though?"
    b "On the one hand, if I'm withholding information that makes me look bad."
    b "If this ties Shahar to the location, based on the past two locations doesn't that make him more likely to be the murderer?"
    b "On the other hand, this is Shahar's personal life."
    b "I guess it's not really news to anyone that this whole pirate thing is a bit crazy but..."
    b "If it's a red herring it could be problematic."
    b "Plus, with this few people remaining, it's hard to trust anyone."
    b "..."
    b "I don't think I'll tell anyone except Shahar."
    b "I feel sorry for Shahar... I don't want to give people reason to gang up their suspicions on him."
    b "There's no way the Game Master would make it this obvious who they are."
    b "So I can trust him, right?"
    b "And hopefully this way he can trust me."
    b "I guess I'm done here. Doesn't look like there's any other patients of interest in this program."
    b "Time to go check the other door in the guard common area."
    scene black with dissolve
    bi "I made my way through the common area to the other room."
    scene bg hospcloset
    b "Huh, a supply closet."
    b "I guess even a mental hospital needs to get cleaned every now and then."
    b "It's a bit dark in here, let me turn on the lights."
    b "...actually, after reading that sign, maybe I won't."
    b "Don't want to die for forgetting to flip a light switch."
    b "Let's see. There's a box of small unzippable plastic bags on the top shelf, fairly standard."
    b "Maybe they use those to distribute medicine here?"
    b "The second shelf has a variety of cleaning supplies."
    b "Ammonia, bleach, ethanol, hydrogen peroxide..."
    b "All fairly standard stuff. I guess a mental hospital has less biohazards than a medical hospital."
    b "Below that, there's a stepstool. Maybe for maintenance workers?"
    b "And... a baseball bat."
    b "That's not ominous at all..."
    b "Should I hide it? It's such an obvious choice for a murder weapon."
    b "No, there's a rule that says it needs to be returned here."
    b "I don't really want to be the one to test if hiding it gets me killed..."
    b "I guess... I'll just leave it here and let the others know so we're all vigilant about it."
    b "It can be like the kitchen knife in the mansion. If everyone's keeping an eye on it it's not a threat."
    b "I think that's all I have to explore here, time to head to the kitchen."
    scene black with dissolve
    scene bg hospkitchen with dissolve
    show jenny happy with dissolve
    j "Hey Bert, what'd you find?"
    b "Well, there's what looks like a control or security room."
    b "Giant computer, can look at the cafeteria from there."
    b "And some archives from this place."
    bi "I shouldn't tell her about Shahar..."
    b "Nothing too interesting though."
    b "And then there's a closet with various cleaning supplies."
    b "I hope we won't have to use them..."
    b "Oh, and a baseball bat."
    show jenny ind
    j "A baseball bat?"
    b "Yeah... not sure why a mental hospital has a baseball bat in a supply closet."
    j "I can uh... think of some not-so-great reasons."
    b "Oh."
    b "Ohhhhh. This place just got a lot darker."
    j "Should we take the bat and put it somewhere where everyone can see it?"
    b "There's a sign in the closet that says to return everything... I'm afraid if we move it we die."
    b "That's what seems to be the punishment for not following the rules in the cafeteria."
    j "That sucks. Well, guess we'll just tell everyone."
    b "How's cooking going?"
    j "It's okay. This kitchen is not nearly as well stocked as the mansion was."
    j "The fridge only has the bare minimum, basic veggies like tomatoes and onion, a few broths."
    j "The pots and pans are huge though, I guess because they're used to cooking for a large group."
    j "So I'm cooking a big pot of tomato soup right now."
    j "Nothing too fancy but that's about all I know how to do."
    b "Can't say I have any fancier ideas..."
    b "Anything I can do to help?"
    j "Hmm, actually, do you mind if I explore a bit now that you're here?"
    j "You'd just need to stir the pot every now and then, I can try to be back before it's done cooking."
    b "Sure, this would be a good chance for me to catch up with the others anyway."
    show jenny happy
    j "Thanks Bert! Just to be safe, if it feels like 20 minutes have passed since I've left turn off the stove then."
    b "Got it, let me know if you find anything I missed."
    j "Will do, seeya Bert!"
    hide jenny with dissolve
    bi "I guess I haven't talked to the others yet..."
    bi "I turned to the window and started chatting with the first person I saw."
    show drac ind with dissolve
    d "Hello Bert. Are you here to brief us on the other side?"
    b "Uh... I guess I can, yeah."
    d "Let me gather the others then, so you don't have to reexplain anything."
    hide drac with dissolve
    show frog ind with dissolve
    f "Bert! Are you okay?"
    b "Oh, hey Freddy. Yeah I'm fine."
    show frog sad
    f "I got worried because Jenny showed up but you didn't."
    f "And I thought... well..."
    bi "Freddy looked like he was on the verge of tears."
    bi "Despite us trying to keep death away from him, he might have been thinking about it as much as the rest of us."
    bi "Though maybe he didn't grasp how obvious it would be if Jenny murdered me on the first day..."
    b "I'm here Freddy, don't worry!"
    show frog ind
    f "Oh. Okay. Is the food almost ready?"
    bi "Children really are whimsical."
    show frog ind:
        xcenter .5
        linear 0.15 xcenter .25
    show drac ind:
        xcenter .75
    with dissolve
    bi "Dracula had gathered the others, except for Sam, and returned to the window."
    d "Bert, you may begin your explanation."
    b "Alright..."
    bi "I briefly told them about the common area, control room, and supply closet."
    f "Baseball bat? Can we play sports in here?"
    b "I uh... didn't see any baseballs or anything like that in here."
    f "Oh. Maybe we can find one!"
    d "Hush child, there are business matters to discuss."
    d "So you say you're afraid to take the baseball bat out of the closet?"
    b "Yeah, there's a sign saying to return everything."
    b "I don't want to find out if breaking that rule kills me like the other rules."
    d "It seems unlikely, you could just try taking it out and see what happens."
    bi "Easy for you to say when you're on the other side..."
    d "So there was no information in the control room of use?"
    b "Nothing I saw, no. Though there are a lot of patients in the records so I didn't scroll through them all."
    bi "That should cover my bases..."
    d "Perhaps if you feel like helping the group, you could sift through the records with the rest of your free time today?"
    b "Uh..."
    hide frog with moveoutleft
    show lauren ind with moveinleft:
        xcenter .25
    l "Don't make him waste his time, you've done enough for him already Bert."
    l "If you really wanna know, you can check on your own time Dracula."
    d "Hmph. Fine."
    b "By the way, I heard the 5 minute reminder get announced this morning..."
    b "Did everyone make it out of their cells in time?"
    l "Yeah, we had to do some... convincing to get Sam out of bed."
    b "Is Sam doing any better?"
    l "Not really. Mostly just sitting in the same seat."
    b "That's... a little concerning, to put it lightly."
    l "Yeah. Don't worry about it for now, not much you can do on that end."
    l "By the way, where's Jenny? Isn't she prepping a meal right now?"
    bi "Shoot!"
    b "Uh... yeah, I gotta go take care of that."
    b "We'll let you guys know when it's ready."
    hide lauren
    hide drac
    with dissolve
    bi "I turned to the soup and started stirring it."
    bi "After about 10 minutes, Jenny returned."
    show jenny happy with dissolve
    j "Hey Bert! Everything okay here?"
    b "Yup! Was definitely sitting here making sure nothing burned the whole time!"
    show jenny ind
    j "...You're acting suspicious."
    b "Okay, I may have not stirred the soup until a few minutes after you left."
    j "Bert, it's tomato soup. Not a steak or anything like that."
    j "Worst case we just don't serve the burnt soup at the bottom."
    j "As long as Sesame didn't vomit in the soup or anything like that."
    b "Oh shoot, I totally forgot about Sesame!"
    bi "I quickly scanned the room to locate him."
    bi "Thankfully, Sesame was just curled up on one of the tables sleeping."
    bi "I guess cats are known for sleeping a lot..."
    b "Did you find anything?"
    j "Nope. I thought about looking through the records but then I decided it was too boring."
    j "Besides, I'm sure if there were something interesting you would have found it."
    show jenny happy
    j "Oh! But there is something secret in here!"
    b "What?"
    j "Check the fridge, second level from the top."
    bi "I opened the fridge and found..."
    bi "A cupcake."
    bi "Red velvet with what looked like cream cheese frosting..."
    show jenny ind
    j "There were two when I found them but uh..."
    show jenny happy
    j "Well, one of them magically disappeared!"
    bi "A likely story."
    j "Anyway Bert, you should have the other one."
    j "No one else will know, unless the next guards dig through the trash."
    j "And you deserve a reward for all the hard work you've put in!"
    b "Jenny... I don't know, it feels like I'd be lying to the others out there."
    b "Shouldn't we try to build trust instead of hiding something from them?"
    show jenny ind
    j "It's just a cupcake Bert, it's not a big deal."
    j "It's not like hiding our pasts or how we're criminals."
    j "You're making me feel bad for having a giant sweet tooth..."
    b "No, I'm not trying to make you feel bad!"
    bi "I hate these types of scenarios."
    bi "Where you don't personally feel like you could do something but can understand why others do."
    bi "Like being the vegetarian friend who watches their friends eat meat."
    bi "Or not caring much about social media but your friends are upset when you don't like their posts."
    menu:
        "What should I do?"

        "Eat the cupcake":
            $eat = True
            b "Okay, you're right, it's not a big deal."
            b "And I have been \"carrying the team\" so to speak."
            b "Besides, for all we know the Game Master will restock the fridge tonight."
            bi "I didn't actually believe that, but I said it to make her feel better."
            show jenny happy
            j "Yay! Dig in Bert, you deserve it!"
            bi "I unpeeled the wrapper and started biting into the cupcake."
            bi "I won't lie, if only for a split second, the taste of frosting made me feel happy."
            b "Oh Jenny, I never talked to you about the whole Mr. Sydell thing."
            b "I take it you never met him?"
            show jenny ind
            j "Nope, haven't heard the name until now."
            j "Do you know anything, Bert?"
            b "I don't, but Stella told me something while we were in the mansion."
            b "She said something about how she \"hires suits to step on guys like him.\""
            j "...What does that mean?"
            j "..."
            j "Oh! I remember once seeing on TV something about how Cantoire Holdings sued a smaller company."
            j "They failed to fulfill an order by one of their clients owned by Cantoire Holdings."
            j "So Cantoire Holdings sued them."
            j "They won the lawsuit, and the smaller company couldn't pay out so they went bankrupt."
            j "Do you think that's what she meant?"
            b "Maybe... do you think Mr. Sydell owns a company like that?"
            j "No clue. But it would make sense."
            j "Maybe this whole game is orchestrated by him as revenge on Stella?"
            j "If he owns a company he would have the money to put together something like this."
            b "Why are the rest of us here though?"
            b "Not like I helped Stella take down any company..."
            b "I'd never met her before this happened."
            b "And now Stella's dead, couldn't the game just be over."
            j "Hm... maybe this theory is wrong then?"
            b "Maybe. There's other ways to be rich enough to host this kind of game and be upset at Stella."
            b "I'd imagine many people in the world are already upset at a CEO like Stella anyway."
            b "For all we know this is some vigilante justice against random criminals with no connection..."
            j "I don't think it's a coincidence Mr. Sydell keeps coming up though."
            b "You're right, I'm just... speculating, I guess."
            j "Oh, looks like the soup is almost done!"
            j "Want to help me serve it, Bert?"
            b "Yeah, let's do it."
            jump postcupcake

        "Tell the others about the cupcake":
            $eat = False
            b "Sorry Jenny... I think I'm going to tell the others about it."
            b "See if any of them want it more than I do."
            j "Bert... they're all going to hate me if they know I ate it without telling them!"
            b "If you want I won't tell them you ate one. I'll just say there was only one."
            b "I don't think they'll have a reason to think we're lying if I give them one cupcake."
            j "Hmph. Okay."
            bi "She turned away from me and stirred the soup."
            bi "I think she was upset, but I don't feel like I did anything that merited it..."
            bi "We sat there in silence, her cooking, me staring at the wall, until she was done."
            bi "Well, hopefully this will blow over soon."
            bi "Time to serve the meal..."
            jump postcupcake
label postcupcake:
    bi "Hm... I should try to find a way to talk to Shahar discreetly while everyone's eating."
    j "Food's ready!"
    show jenny ind:
        xcenter .5
        linear .15 xcenter .25
    show sid ind with moveinright:
        xcenter .75
    
